特征提取,找到时间断点

In [80]:
import numpy as np
import matplotlib.pyplot as plt
import sklearn
import csv
import pandas as pd

import datetime
import time
import skimage


from sklearn.metrics.pairwise import pairwise_distances #计算坐标点距离

def get_diff(ls):
  diff = []
  num = 0
  for index,data in enumerate(ls):
    if index+1<len(ls):
      m = [ls[index],ls[index + 1]]
      diff_1 = pairwise_distances(m)[0,1]
      print(diff_1)
      diff.append(diff_1)
      if diff_1 <0.1:
        num= num+1

  print(num)
  return diff

def get_breakPoint(data):
    """通过计算空间中坐标点的距离来判断是否使用手机"""
    coordinate = data[:,1:4] # 三维坐标轴
    length = coordinate.shape[0]
    sample_length = int(length/100)
    '''多的数据不要'''
    coordinate = data[0:sample_length*100]
    coordinate = coordinate.reshape(-1,100,3)

    return coordinate

In [81]:

data = pd.read_csv("u001_w001/u001_w001_accelerometer.log",delimiter="\t")
data = np.array(data)

coordinate = data[:,1:4]
# get_diff(coordinate[0:1000]),coordinate.shape
coordinate = get_breakPoint(coordinate)
coordinate.shape

(319, 100, 3)

In [64]:
Time = data[:,0]
Time = list(map(lambda x:int(str(x)[0:9]),Time))
Time

[924312945,
 924312954,
 924312962,
 924312971,
 924312979,
 924312987,
 924312996,
 924313004,
 924313012,
 924313021,
 924313029,
 924313038,
 924313046,
 924313054,
 924313063,
 924313071,
 924313080,
 924313088,
 924313096,
 924313105,
 924313113,
 924313122,
 924313130,
 924313138,
 924313147,
 924313155,
 924313164,
 924313172,
 924313180,
 924313189,
 924313197,
 924313206,
 924313214,
 924313222,
 924313231,
 924313239,
 924313247,
 924313256,
 924313264,
 924313273,
 924313281,
 924313289,
 924313298,
 924313306,
 924313315,
 924313323,
 924313331,
 924313340,
 924313348,
 924313357,
 924313365,
 924313373,
 924313382,
 924313390,
 924313399,
 924313407,
 924313415,
 924313424,
 924313432,
 924313440,
 924313449,
 924313457,
 924313466,
 924313474,
 924313482,
 924313491,
 924313499,
 924313508,
 924313516,
 924313524,
 924313533,
 924313541,
 924313550,
 924313558,
 924313566,
 924313575,
 924313583,
 924313592,
 924313600,
 924313608,
 924313617,
 924313625,
 924313634,
 924

In [65]:
from pandas.api.types import is_numeric_dtype

def get_time_stamp16():
  # 生成16时间戳  eg:1540281250399895  -ln
  datetime_now = datetime.datetime.now()
  print(datetime_now)

  # 10位，时间点相当于从UNIX TIME的纪元时间开始的当年时间编号
  date_stamp = str(int(time.mktime(datetime_now.timetuple())))

  # 6位，微秒
  data_microsecond = str("%06d"%datetime_now.microsecond)

  date_stamp = date_stamp+data_microsecond
  return int(date_stamp)


#1970-01-01以来的秒数  前10位为秒数，后6位为微秒
def stampToTime_16(stamp):
  datatime = time.strftime("%Y-%m-%d %H:%M:%S",time.localtime(float(str(stamp)[0:9])))
  datatime = datatime+'.'+str(stamp)[9:]
  return datatime

def stampToTime_15(stamp):
  datatime = time.strftime("%d %b %Y %H:%M:%S GMT", time.gmtime(stamp / 100000.0)).split(' ')
  return datatime

In [66]:
Time =list(map(lambda x:stampToTime_16(x),data[:,0]))
Time

['1999-04-17 09:35:45.848402.0',
 '1999-04-17 09:35:54.240736.0',
 '1999-04-17 09:36:02.633070.0',
 '1999-04-17 09:36:11.025404.0',
 '1999-04-17 09:36:19.417738.0',
 '1999-04-17 09:36:27.810072.0',
 '1999-04-17 09:36:36.202406.0',
 '1999-04-17 09:36:44.594740.0',
 '1999-04-17 09:36:52.987074.0',
 '1999-04-17 09:37:01.379408.0',
 '1999-04-17 09:37:09.771742.0',
 '1999-04-17 09:37:18.164076.0',
 '1999-04-17 09:37:26.556410.0',
 '1999-04-17 09:37:34.948744.0',
 '1999-04-17 09:37:43.341078.0',
 '1999-04-17 09:37:51.733412.0',
 '1999-04-17 09:38:00.125746.0',
 '1999-04-17 09:38:08.518080.0',
 '1999-04-17 09:38:16.910414.0',
 '1999-04-17 09:38:25.302748.0',
 '1999-04-17 09:38:33.695082.0',
 '1999-04-17 09:38:42.087416.0',
 '1999-04-17 09:38:50.479750.0',
 '1999-04-17 09:38:58.872084.0',
 '1999-04-17 09:39:07.264418.0',
 '1999-04-17 09:39:15.656752.0',
 '1999-04-17 09:39:24.049086.0',
 '1999-04-17 09:39:32.441420.0',
 '1999-04-17 09:39:40.833754.0',
 '1999-04-17 09:39:49.226088.0',
 '1999-04-

In [67]:
data_time = data[:,0]
data_time.shape,data_time

((31977,),
 array([9.24312946e+14, 9.24312954e+14, 9.24312963e+14, ...,
        9.24581282e+14, 9.24581291e+14, 9.24581299e+14]))

In [68]:
def get_diff(ls):
  diff = []
  for index,data in enumerate(ls):
    if index+1<len(ls):
      diff.append(ls[index+1]-ls[index])
  return diff

diff1 = np.array(get_diff(list(data_time)))
print(diff1.shape)

diff1[257:259],diff1.shape

(31976,)


(array([8392334., 8392334.]), (31976,))

In [69]:
diff2 = np.array(get_diff(diff1))
interrupt_index = []
print(diff2.shape)
for index,value in enumerate(diff2):
  if value not in [-1,0,1]:
    print(value)
    interrupt_index.append(index)
interrupt_index.insert(0,0)
interrupt_index.append(len(diff2))

print(interrupt_index)
print(len(interrupt_index))

(31975,)
4967.0
-4967.0
-7416.0
7416.0
3534.0
-3534.0
-6585.0
6585.0
7032.0
-7032.0
1565.0
-1565.0
14041.0
-14041.0
-12097.0
12097.0
2529.0
-2529.0
-12012.0
12012.0
-4138.0
4138.0
21148.0
-21148.0
-11389.0
11389.0
3654.0
-3654.0
6551.0
-6551.0
-7863.0
7863.0
4755.0
-4755.0
-7811.0
7811.0
3431.0
-3431.0
-15985.0
15985.0
10466.0
-10466.0
-5306.0
5306.0
10002.0
-10002.0
-10273.0
10273.0
14945.0
-14945.0
-3429.0
3429.0
-16124.0
16124.0
[0, 311, 312, 1502, 1503, 2695, 2696, 3886, 3887, 5078, 5079, 6269, 6270, 7462, 7463, 8653, 8654, 9845, 9846, 11037, 11038, 12228, 12229, 13420, 13421, 14612, 14613, 15804, 15805, 16996, 16997, 18188, 18189, 19380, 19381, 20573, 20574, 21764, 21765, 22956, 22957, 24148, 24149, 25339, 25340, 26531, 26532, 27724, 27725, 28914, 28915, 30106, 30107, 31297, 31298, 31975]
56


将数据分成27份,获取27份的特征  x,y,z  均值,方差   27x   3x2    每次  6个x (6份) 个特征


924315522294935	-8.653793	7.4411774	2.372116
924315530687269	-8.083496	7.050354	2.4129944
924315539079603	-7.8804016	6.655731	2.6375275
924315547471937	-7.9380035	6.3203583	2.7997742
924315555864271	-8.132324	6.2790833	2.9280396
924315564256605	-8.244293	6.651062	2.965973
924315572653906	-8.037338	7.2169952	2.6816406
924315581046240	-7.7401276	7.5509796	2.474884


In [70]:
number = [924315522294935,924315530687269,924315539079603,924315547471937,924315555864271,924315564256605,924315572653906,924315581046240]
number1 = get_diff(number)
number2 = get_diff(number1)

In [71]:
number1,number2
# 问题，时间差异变化是  毫秒级别的，是否为异常误动

([8392334, 8392334, 8392334, 8392334, 8392334, 8397301, 8392334],
 [0, 0, 0, 0, 4967, -4967])

In [72]:
data[310:315,0],diff1[310:315],diff2[310:315]

(array([9.24315547e+14, 9.24315556e+14, 9.24315564e+14, 9.24315573e+14,
        9.24315581e+14]),
 array([8392334., 8392334., 8397301., 8392334., 8392334.]),
 array([    0.,  4967., -4967.,     0.,     0.]))

数据分析发现,此数据为传感器定时采集数据,时间间隔为8.392334 秒  与论文描述的数据有误
其中有27个时间异常变动,但变动均为毫秒级别改动 大概率为异常变化 8.392334+0.016124
目前